### ISSUE TITLE
19 lesson

### ISSUE THREAD

**Issue by kl2karpenko** [maxudka/DZ_Kalashnik#3]
Кратко но со вкусом у тебя ДЗ)

В общем:

console.log(Number(‘9’) + 9); можно и так но вот так вот проще console.log(+‘9’ + 9);

в последнем задании главное что бы ты понял почему там получилось undefined и 9

**Comment by maxudka** [comment]
Мерси за комлиман, Лиличка)

Просто сначала Number(val) нашел, потом уже на уроке про унарный плюс
вспомнил))

В последнем, по-крайней мере я думаю, что понял) Но не факт...

9 июня 2016 г., 8:28 пользователь Karpenko Lily notifications@github.com
написал:
